import Head from 'next/head';
import { Button, Container, Typography } from '@mui/material';

const HomePage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
            </Head>
            <main>
                <Container>
                    <Button>Hola</Button>
                    <Typography>NEXTJS-</Typography>
                </Container>
            </main>
        </>
    );
};

export default HomePage;
