import Head from 'next/head';
import { Button, Container, Typography } from '@mui/material';
import { ProductList } from '@/components/Product/ProductList';

const HomePage = ({ productList }: {productList: TProduct[]}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
            </Head>
            <main>
                <Container>
                    <ProductList products={productList}/>
                    {/* <Button>Hola</Button>
                    <Typography>NEXTJS-</Typography> */}
                </Container>
            </main>
        </>
    );
};


import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const response = await fetch('http://localhost:3000/api/avo');
    const { data: productList }: TAPIAvoResponse = await response.json();
    return {
        props: {
            productList,
        }
    }
}

export default HomePage;
